# [![Build Status](https://travis-ci.org/dex4er/Thrall.png?branch=master)](https://travis-ci.org/dex4er/Thrall)[![CPAN version](https://badge.fury.io/pl/Thrall.svg)](https://badge.fury.io/pl/Thrall)

language: perl
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq spell
  - cpanm --with-recommends --installdeps --notest --skip-satisfied git://github.com/dex4er/perl-DEXTER-Module-Skeleton
  - cpanm --with-recommends --installdeps --notest --skip-satisfied .
  - cpanm --force --uninstall IO::Socket::SSL
script: ./Dist.SH
perl:
  - "5.20-extras"
  - "5.20"
  - "5.10"
